### ISSUE TITLE
Webstorm: Unable to authenticate to Team Services.

### ISSUE THREAD

**Issue by wawyed** [Microsoft/vso-intellij#13]
I'm trying to access Team Services through Webstorm and I don't seem to be able to log in. I'm using my personal account.

EDIT: Looking through webstorm logs I found this:

```
2016-05-11 15:30:33,641 [ 239809]   WARN - in.idea.ui.common.LookupHelper - Authenticating with Team Services failed 
java.lang.AssertionError: Unexpected exception type: Microsoft.VisualStudio.Services.Profile.ProfileDoesNotExistException, Microsoft.VisualStudio.Services.WebApi
```

![visualstudioplugin](https://cloud.githubusercontent.com/assets/4390806/15184293/85fc10dc-178c-11e6-9741-e8d6ee26c72b.PNG)

Log in through a browser works perfectly fine.

**Comment by jpricketMSFT** [comment]
Hi wawyed,

Did you ever get past this issue? Did you try upgrading to a newer version of the plugin? We now handle this specific error much better. The only real fix is to force a profile to be created. You can find out more about creating a profile here: http://java.visualstudio.com/Support/faq/Index#_why-do-i-see-the-error-no-profile-exists-for-the-user

Thanks,
Jason
