### ISSUE TITLE
Cannot sign-in to Team Services

### ISSUE THREAD

**Issue by tkralj** [Microsoft/vso-intellij#147]
When I try to import project into Team Services Git i Have to Sign In. When i click on "Sign In" link all i get is blank Oauth request screen and i cannot enter my username and password.

**Comment by mfilippov** [comment]
@tkralj Which version of IDE are you use?

**Comment by mfilippov** [comment]
I saw same issues when IDE used not bundled JDK.

**Comment by kottalovag** [comment]
Me too. I use PyCharm 2017.3.3 Community Edition.
An empty white window with the title OAuth 2.0 Authorization Request.
Actions which reproduce this: sign in or pull/push existing repo.

Funny thing, I am able to pull/push the repo using the Terminal inside PyCharm.
I also tried tampering with the proxy settings - to no avail.
OS: Win10 customized (restricted) by company.

**Comment by whoisj** [comment]
@tkralj @kottalovag can you use a tool like Fiddler to capture the HTTP traffic? This will help us look what is actually happening.

**Comment by tkralj** [comment]
I had more than one Java version installed and that may confused IDE. I uninstalled all Java versions and JDKs and reinstall only last version. After that everything started to work. Thanks all for help!
