### ISSUE TITLE
Unable to get Work Items until 1hr after creation

### ISSUE THREAD

**Issue by rnbayliss** [Microsoft/vso-intellij#15]
I am trying to see the work items for our TFS project and I have run into an issue where the plugin is querying the TFS API providing a parameter "asOf" which is 1hr behind my local time (BST) and this results in a 404 result.

It is clearly something to do with the timezone; the request going out in GMT not BST and our TFS 2015 server is interpreting it as BST. This means the work item "doesn't exist" and so I cannot associate through the UI. Using #{task id} does associate on checkin mind you.

Can this be resolved? I am on version _v0.100.1 Preview_ and this is a real shopstopper for my team. I have tried to pull the source, rectify and build myself; but I cannot get the project to work in Intellij latest (2016)

**Comment by jpricketMSFT** [comment]
Hi rnbayliss,

Thanks for reporting this issue. We will try to reproduce the issue and get a fix in as soon as possible. If you think of any other details, please let us know. I will try this out today.

Thanks,
Jason

**Comment by rnbayliss** [comment]
I can provide a wireshark trace if needed of the affected packets..?

**Comment by jpricketMSFT** [comment]
I will let you know if we need those. I hope we can repro the issue today. If so, a fix will go out with our next deployment.

**Comment by rnbayliss** [comment]
Fantastic, thanks. I look forward to it.

**Comment by jpricketMSFT** [comment]
I was able to repro the problem (after changing the Time Zone of the account that TFS was running as) and found the problem. Thanks for reporting this issue. The fix should be released in the next week or two.

**Comment by richbayliss** [comment]
Thanks Jason, I look forward to trying this out. I'll try pulling the latest code with the commit above and see if I can get it working. Looks like the solution was to remove the "asOf" parameter, was this a mistake in code or simply an easy fix to get all work items?

**Comment by rnbayliss** [comment]
Thanks Jason, I look forward to trying this out. I'll try pulling the latest code with the commit above and see if I can get it working. Looks like the solution was to remove the "asOf" parameter, was this a mistake in code or simply an easy fix to get all work items?

**Comment by jpricketMSFT** [comment]
It was a coding mistake on my part. I didn't test the asOf date with different time zones. The only advantage to using the asOf date would be if somehow the work items changed between the two server calls and you wanted to show the exact work item details that were there when you made the first call. I don't think we need that kind of precision here :)

Thanks again for reporting the issue and trying out the fix!

**Comment by rnbayliss** [comment]
Jason, I have built the master branch and I will try the plugin tomorrow at work. One thing, it is frustrating to have to install IntelliJ 14.x when 2016 is now available. Are there plans to migrate to the 2016 plugin model soon, or is this something you would like assistance with from the community?

**Comment by jpricketMSFT** [comment]
That's a great question. We should probably update our docs. 15.x should work perfectly fine. We have a backlog item to get everything working on 16, but it isn't there yet. Help from the community is always welcome :)

**Comment by rnbayliss** [comment]
I tried the plugin today (built in manually against v14 and installed into v2016) and the Work Items showed up straightaway. Cheers.

**Comment by jpricketMSFT** [comment]
Thanks, Rich!
