### ISSUE TITLE
No support for tasks

### ISSUE THREAD

**Issue by joedborg** [Microsoft/vso-intellij#16]
For me, the biggest benefit for this plugin is to share tasks with IntelliJ (et. al.).  I feel most of the features this plugin currently brings can be achieved with the built-in Git support.  Only the pull requests seem to be the exception (which is a really useful thing).

When using JIRA as a task server, one can pick their bug / PBI from a list, which then creates a branch based on the item's ID and then appends it to each commit so they can be seen on the item in JIRA.

**Comment by yacaovsnc** [comment]
Thanks for your feedback Joe!  The latest version of the plugin has a "work item" tab which shows all the tasks assigned to me in a list.  We are actively working on creating a branch from any of the work items now.  :)  It should be available very soon.  

Thanks again for using our plugin, and we really appreciate the feedback.

**Comment by joedborg** [comment]
Hi Yang,

Thanks very much for the rapid reply and it's really nice to see Microsoft releasing open source developer tools. 

Could you tell me how to display this tab as I can't seem to find it :)

Do you know if this plugin will ever interact directly with IntelliJ's task manager?  Or will it always be a seperate entity?

**Comment by yacaovsnc** [comment]
Hi Joe, 

Sure!  Please make sure you have plugin version 0.100.1 installed.

Then you should see this "Work Item" tab inside the "Version Control" tab.
![image](https://cloud.githubusercontent.com/assets/10119737/15717832/bb115b5e-27f6-11e6-9b27-97d8d0c1ec13.png)

Currently we are not integrated with IntelliJ's task manager.  Thanks for this valuable feedback, I will definitely rely the message to our team.

**Comment by joedborg** [comment]
Ah yes thanks, I've found it now.

Thanks for relaying the feedback, it would be nice to leave this open until that is done.

**Comment by DavidStaheli** [comment]
Hi @joedborg, after talking with JetBrains, we're working on a strategy that may not integrate with IntelliJ's task manager.  I'm going to close this issue for now.

**Comment by pmoskvin** [comment]
@DavidStaheli, how is it going?

**Comment by maciekkukuczka** [comment]
HI! Is there a chance to integrate with Jet Brains Task Manager?
<Please...>
