### ISSUE TITLE
Code Review tool like visual studio

### ISSUE THREAD

**Issue by rohitramkumar308** [Microsoft/vso-intellij#17]
You guys are doing a great job with this plugin. Are you planning on integrating code reviews like in visual studio ?

**Comment by jpricketMSFT** [comment]
Hi Rohit,

That's a great question. The first thing we need to do is get TFVC integration. Currently, we only have Git integration with VSTS and TFS. Once we have TFVC working (hopefully soon), we will consider things like Code Review. However, it is not on the radar right now.

Thanks for asking!
Jason
