### ISSUE TITLE
Cannot see the team services under VCS in android studio

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/vso-intellij#21]
I have disabled the plugin and re-enabled. But I cannot see those in my android studio.

**Comment by jpricketMSFT** [comment]
Hi Srivatsa, 
Can you describe exactly what you are doing and what you expect to see? There are cases were authentication keeps some accounts from showing up. If you know your VSTS account url, you can go to the Team Foundation Server tab of the login dialog and put in the account url directly there.
Thanks,
Jason

**Comment by SrivatsaMarichi** [comment]
Hi Jason,

I'm sorry for the delay in response. Now i am able to see those in my Android Studio!

Thanks,
Srivatsa
