### ISSUE TITLE
Function result is ignored

### ISSUE THREAD

**Issue by AppChecker** [Microsoft/vso-intellij#23]
Hello!

Code in the method [UrlHelper.getFileURI](https://github.com/Microsoft/vso-intellij/blob/bb3910bba15a933e76c3ca5ba85c3437d2e2d602/common/src/com/microsoft/alm/common/utils/UrlHelper.java#L251):
```
        if (StringUtils.isNotEmpty(gitRemoteBranchName)) {
            uri.concat(URL_GIT_VERSION_SEGMENT).concat(gitRemoteBranchName);
        }
```
ignores the return value of the String.concat method.

Probably, is should be:

```
        if (StringUtils.isNotEmpty(gitRemoteBranchName)) {
            uri = uri.concat(URL_GIT_VERSION_SEGMENT).concat(gitRemoteBranchName);
        }
```

This possible defect found by [static code analyzer AppChecker](http://cnpo.ru/en/solutions/appchecker.php)

**Comment by leantk** [comment]
Thanks for bringing this to our attention.

Fixed in commit c5cc5d919cf8976b64fa256d0fc1f809494d55a8
