### ISSUE TITLE
Unable to create workspace.

### ISSUE THREAD

**Issue by Hirr0** [Microsoft/vso-intellij#25]
Windows 10
Installed plugin, Cross-Platform Command-Line (TF), JDK, accepted tf eula, added JAVA_HOME and TF_HOME system variables. Signed in to vsts. Can choose a project from list.
When i click create workspace, popups window with a status of creating workspace, then i get error:
KEY_TF_BAD_EXIT_CODE
com.microsoft.alm.plugin.external.exceptions.ToolBadExitCodeException: KEY_TF_BAD_EXIT_CODE
    at com.microsoft.alm.plugin.external.tools.TfTool.throwBadExitCode(TfTool.java:86)
    at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:135)
    at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:239)

On another machine (Windows server 2012 r2) when i do same steps, window with a status of creating workspace displays a few seconds, then closes and nothing happens.

Same steps on Windows 7 - works very good.

**Comment by jpricketMSFT** [comment]
Thanks Hirr0 for reporting this issue. We are aware of some problems creating the workspace. We hope to have some fixes out very soon.

**Comment by jpricketMSFT** [comment]
@Hirr0 - Hi, we have pushed out a new update with some fixes in this area. Please take a look and let us if the problem is not fixed. The newest release is v1.107.1. You should be able to update it within the IDE.
Thanks for helping us track down these problems!
Jason

**Comment by Hirr0** [comment]
![image](https://cloud.githubusercontent.com/assets/18056168/19521954/382818ea-961e-11e6-9148-c3eebd5f8046.png)
I've tried to checkout with different directory names, it didn't help.

**Comment by jpricketMSFT** [comment]
Hi Hirr0,
I am sorry to hear that the newest version of the plugin didn't fix your issues. Can you share your logs here? You can find out more about sharing your logs here: http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq 

Thanks,
Jason

**Comment by Gadsha** [comment]
Windows 7, Android Studio 2.1.2

everything looks good, the plugin finds my server and I login to the server, but when I choose my repository and click on "Create Workspace" it freezes.

![tfsnotworking](https://cloud.githubusercontent.com/assets/13866820/19625378/c821de1a-9923-11e6-9913-ed242a37753d.jpg)

**Comment by dertuxmalwieder** [comment]
Confirmed freezing for Windows 10, Android Studio 2.2.2. (Technically not "freezing", I can still move the window, but no progress happens and I can't click anything inside the window anymore.)

**Comment by jpricketMSFT** [comment]
@dertuxmalwieder - Thanks for the confirmation. We hope to get a repro for this problem so that we can address it. Could you provide your Android Studio logs?
Thanks,
Jason

**Comment by dertuxmalwieder** [comment]
Sure thing. Seems like it's just "WAITING" like forever while creating new `threadDump`s every five seconds. I decided to kill Android Studio after I had enough of them.

I'd appreciate it if you deleted the attachment after evaluating. Too many personal data. :-)

[logs.zip](https://github.com/Microsoft/vso-intellij/files/578569/logs.zip)

**Comment by dertuxmalwieder** [comment]
> 2016-11-08 16:28:52,967 [  35182]   INFO - n.context.ServerContextManager - validateTfvcUrl: failed to get collection info 

Could be relevant here. The last line before the dumps. For some reason connection works only before that.

**Comment by jpricketMSFT** [comment]
@dertuxmalwieder - I downloaded the file and removed the file link. Thanks for providing that. If you want to increase the memory for Android Studio you can follow these steps:

If your logs have a lot of “High memory usage (free 88 of 1246 MB)” statements, you may want to increase the amount of memory available to Android Studio.
1)	Go to Help->Custom VM Options…
2)	Create a custom VM options file when prompted
3)	And add 2 lines with the values you want (the default max is 1280): 
-Xms1280m
-Xmx4096m

I am looking at the logs now and will hopefully find something we can use to repro and fix the issue.
Thanks,
Jason

**Comment by dertuxmalwieder** [comment]
This machine is not too new, I'm happy that Android Studio works at all :-). A higher memory usage would probably be disturbing. (Especially since I'm not the only developer of this project and the other one has a number of VMs open most of the time.) But thank you, we'll discuss that.

Let me know if I can help you further.

**Comment by dertuxmalwieder** [comment]
FYI: Still broken in the latest update.

**Comment by jpricketMSFT** [comment]
@dertuxmalwieder - Unfortunately, the logs only showed a "Service not available" error. Nothing more can really be determined. If possible could you try using the IP address of the server instead of the name? Something like http://10.16.18.02:8080/tfs
And make sure you can reach the same url thru the browser on that machine.
Are you using an http proxy? We have a known issue with proxies.

Thanks,
Jason

**Comment by dertuxmalwieder** [comment]
Yes, I'm behind an intranet proxy, but Android Studio actually uses it...?

**Comment by Hirr0** [comment]
With verison 1.111.1 it works. Only one nuance: In JetBrains Rider - works out of the box, but in IntelliJ or WebStorm i have to change **java -Xmx2048M** to **java -Xmx512M** in tf.cmd file . Can't understand why, because i have 16GB memory on my machine and half of it is free.
Close please, if it's needed. thank you.

**Comment by leantk** [comment]
Thanks for validating the fix and letting me know about the difference between Rider/IntelliJ/WebStorm. I will look into that and see if I can figure out why the memory would need to be changed.

**Comment by Nerves82** [comment]
Hello. This problem still exists.
