### ISSUE TITLE
Custom workspace

### ISSUE THREAD

**Issue by ayushindin** [Microsoft/vso-intellij#29]
Hi. 
Thank you for your great work. 
I have a question about opportunity to create custom workspace. My project build from different sources which are located in different repositories. Does is it possible?

**Comment by jpricketMSFT** [comment]
@ayushindin - Yes this is possible. This is not the expected scenario, but you can modify your workspace to include any server paths you want in the Edit Workspace dialog. You can choose VCS->TFVC->Edit Workspace OR you can click the checkbox to Edit the workspace on the VCS Checkout dialog. Let us know if you have any issues with this type of workspace.
Thanks,
Jason

**Comment by ayushindin** [comment]
@jpricketMSFT It will be great if I have opportunity to checkout project by specific workspace. 
I tried to:
1) enable vcs integration for existing project - workspace is empty; If edit workspace than "Updating workspace: error current workspace"
2) checkout empty repository -> modify workspace -> list all dependencies (can't copy workspace from tfs or copy-past text...)

**Comment by jpricketMSFT** [comment]
@ayushindin - I am not sure I understand what you want to do. Can you edit the workspace? What do you mean by repository? I assumed you meant different team projects in the same Collection. All of the sources in a particular workspace have to come from the same collection. Perhaps a few screenshots would help me understand your scenario better.
Thanks,
Jason

**Comment by ayushindin** [comment]
@jpricketMSFT 

First case: 
Preconditions: I have a real project which mapped from TFS. I opened, then enable vcs integration and try modify workspace.

1) ![image](https://cloud.githubusercontent.com/assets/5469288/19442894/9dda9780-9493-11e6-935d-004df793b22e.png)
2) ![image](https://cloud.githubusercontent.com/assets/5469288/19442940/c62d31c0-9493-11e6-95d6-f0e6d71ad159.png)
3) ![image](https://cloud.githubusercontent.com/assets/5469288/19442965/df812726-9493-11e6-8cc7-21c05dc34e61.png)

**Comment by jpricketMSFT** [comment]
@ayushindin - That's a really bad error message. My apologies for that. Could you look in the Log file (under help menu) and attach the callstack for that error here?
How did you create the workspace on disk? Did you use the Java command line version of TF or some other way? You will probably have to recreate the workspace using the Java command line version of TF or Android Studio.
Thanks for the screen shots, they really helped me understand the problem.
Jason

**Comment by ayushindin** [comment]
@jpricketMSFT My steps:
1) I create workspace in TFS app.
2) Open downloaded project with Android Studio.
3) Enable VCS integration 
4) Try to modify workspace. Workspace is empty and i can't to change it (screenshots)

Maybe problem between TFCommandLine and Visual Studio (TFS).

**Exception:** 
java.lang.RuntimeException: An argument error occurred: The workspace could not be determined from any argument paths or the current working directory.
	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:333)
	atcom.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:49)
	atcom.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:20)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:142)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:290)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:328)

**Comment by jpricketMSFT** [comment]
@ayushindin - I think you are right. The workspace created by Visual Studio is probably not being recognized by the Java TF command line that we use. Probably because the cache files are in different locations. Can you recreate the workspace in Android Studio?

**Comment by ayushindin** [comment]
@jpricketMSFT Could you provide instruction how to recreate, please?

**Comment by ayushindin** [comment]
@jpricketMSFT Moreover, if I print "tf workspaces" in cmd then I'll see some workaspaces which are the same with workspaces in tfs (visual studio) (not all).

**Comment by ayushindin** [comment]
I sync cache and it helps.

**Comment by jpricketMSFT** [comment]
That's great! Thanks for updating the issue. Let us know if you run into any other issues.
