### ISSUE TITLE
Can't checkin changes

### ISSUE THREAD

**Issue by ayushindin** [Microsoft/vso-intellij#30]
Hello.

I can't checkIn changes. I'm using TFVC. I have a real project which was mapped from visual studio. I opened it with android studio and enable vc integration (workspace is correct). 
![image](https://cloud.githubusercontent.com/assets/5469288/19479402/3148fdac-954f-11e6-9087-4c27dab32431.png)

if skip and try to checkIn:
![image](https://cloud.githubusercontent.com/assets/5469288/19479318/c7ef969a-954e-11e6-9c7c-2144a1047136.png)

Any ideas?

**Comment by jpricketMSFT** [comment]
@ayushindin - How large is your workspace? How many files? If it's more than 100,000, you may be running into some limitations on local workspaces. Then again, this could just be a bug with the (Preview) bits. Can you open the log and see if there are any exceptions? 
Thanks,
Jason

**Comment by ayushindin** [comment]
@jpricketMSFT there are no any exceptions. Also, there are about 85 000 files.

**Comment by ayushindin** [comment]
@jpricketMSFT Does it possible to see history (from server) in android studio? Or it's also bug?

**Comment by jpricketMSFT** [comment]
We haven't implemented the history feature yet :(
85,000 is a lot of files. It could take several minutes to refresh the status, but I would expect it to finish in less than 30 minutes for sure. How long was it stuck like that?

**Comment by ayushindin** [comment]
@jpricketMSFT 26 minutes were enough:-) 
Thank you for your attention. I'll try to provide more information about my experience with your plugin.
My team will be happy when plugin will release with all amazing features. Thank you.
