### ISSUE TITLE
Android Studio with TFVC does not track removing and renaming files

### ISSUE THREAD

**Issue by vbarkov** [Microsoft/vso-intellij#31]
When I try to remove file from Project window in Android Studio it removes but my local changes is empty. So I can't rollback this change. When I update project, removed file doesn't downloaded from server.

When I try to rename file (Refactor->Rename), file with new name appears in Unversioned files. I can add it to change list. But after rollback it appears in Unversioned files or removes. So I can't rollback renaming. After commit I see both files (with old name, and new name)

**Comment by jpricketMSFT** [comment]
@vvb3590 - thanks for the feedback. The problem with removing files looks like a bug. We will try and get a fix for that soon. We have not implemented the rename feature yet. We are working on it soon.
I am going to mark this issue as a bug and a suggestion for tracking.
Thanks,
Jason

**Comment by jpricketMSFT** [comment]
Please give remove a try again. We think we have fixed all the issues with that one.
We are still working on all the rename scenarios.

**Comment by leantk** [comment]
Rename and delete has both been added to the plugin as of version 1.111.1. Please upgrade to that version and if you see any further problems, please reopen this issue.
