### ISSUE TITLE
Android Studio TFVC: Work item linking with commit

### ISSUE THREAD

**Issue by vbarkov** [Microsoft/vso-intellij#33]
Hi.

It is very grate feature in TFS Git to link work item with commit.
Do you plan to add this feature in TFS TFVC?

It will be nice if after commit work item state will be changed to resolved or closed

**Comment by jpricketMSFT** [comment]
Yes, we hope to add the ability to link work items with TFVC checkins soon. As for resolving the work item when you commit, that feature is being worked on by the version control teams. We hope to have something that works for both Git and TFVC at some point.

Thanks for the suggestion!

**Comment by jpricketMSFT** [comment]
We added the ability to associate work items with your TFVC check in. It works the same as it does with Git. You can type in #bugNumber or you can select them from a list if you click on the add work items button.
We do not currently have the ability to "resolve" work items. We will probably add this when Git also supports the feature.
