### ISSUE TITLE
Android Studio TFVC proposal: conditional commit 

### ISSUE THREAD

**Issue by vvb3590** [Microsoft/vso-intellij#34]
Hi

It would be quite good to add a feature which allows to run some tasks (for example gradle tasks with tests or checkstyle) before any commit. 
If one of the tasks will be failed don't perform the commit.

**Comment by jpricketMSFT** [comment]
That's an interesting suggestion. I think you can do certain things before you commit locally. If you are looking for something that would run tests before you merge your changes into main, take a look at the Team Services Pull Request feature. You have the PR run builds, wait for code review sign offs, and more. This is the way I would suggest accomplishing your request.
Thanks for the suggestion!
