### ISSUE TITLE
Android Studio: workspace does not load

### ISSUE THREAD

**Issue by vbarkov** [Microsoft/vso-intellij#35]
Hi.

I am using proxy server to access to Team Foundation Server.
I just change domain password (password to proxy also changed) and I don't load my workspace any more. I tried to restart Android Studio, restart Windows, but it does not help.

UPD: Access denied connecting to TFS server

![workspaceproperties](https://cloud.githubusercontent.com/assets/4267321/19641865/3f0c69ec-99eb-11e6-8064-a697cd0f107a.png)
![checkout](https://cloud.githubusercontent.com/assets/4267321/19641871/44ac980e-99eb-11e6-95a4-3e5f37b7c55c.PNG)

**Comment by leantk** [comment]
Hi vbarkov,

I'm sorry to hear about your issue. So you say it was working for you but then stopped working when you changed your password, correct? If that is the case, the IDE is probably using cached credentials that are no good anymore. Try going to File -> Settings. Search for Password and you should find a menu under Appearances & Behavior like this:

![capture](https://cloud.githubusercontent.com/assets/13628312/19739359/a0a0063e-9b88-11e6-8a67-2c6dd5b63918.PNG)

Choose "Do not remember passwords" and then Apply (remember what you had selected before so you can go back to that). Then go to File -> Invalidate Caches / Restart. Choose to "Invalidate and Restart". When the IDE restarts, you should be prompted for your password again and then you should be able to load your workspace information like before. You can change your password settings back to whatever they were set to before so don't have to continually re-enter them.

Let me know if this work for work for you. Again I'm sorry about the inconvenience and we will look into a better way to deal with rotated credentials. 

Thanks,
-Leah

**Comment by vbarkov** [comment]
Hello, Leah.

Your solution works. Thanks.
I think that plugin must ask user to reenter password in such cases

**Comment by leantk** [comment]
Glad to hear it worked! We definitely have it as a backlog item to fix this issue. You're right, you should just be re-prompted for credentials.

Thanks again,
-Leah
