### ISSUE TITLE
Unable to authenticate to Team Foundation Server

### ISSUE THREAD

**Issue by aleques** [Microsoft/vso-intellij#36]
Hi there

Do I need some specific permission on TFS?
Just the administrator got it and the other here are not adm.

OBS: No logs on intellij about it (com.microsoft.alm)

Proxy here block my login on github.
I would appreciate it if you could provide me some valid email address.
Then, I could send my idea.log

Kind regards
Alex

**Comment by leantk** [comment]
Hi Alex,

If your proxy blocks GitHub then it probably is causing issue for the plug-in as well. You can email me at leantk@microsoft.com with your log and I can help you. If you don't see anything related to Microsoft in the logs, make sure you follow the steps in the last FAQ here to turn on our logging:
http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq

Thanks for reaching out,
-Leah
