### ISSUE TITLE
TFVC: View history in Android studio

### ISSUE THREAD

**Issue by vbarkov** [Microsoft/vso-intellij#40]
Hi,

Are you planning to add the following features:
1. View item history in TFS 
2. Rollback changes in TFS
3. Get specific version from TFS

**Comment by jpricketMSFT** [comment]
We are working on some of those features now. But we also expect users to do more advanced scenarios like getting a specific version on the command line directly. Obviously, we want to have the right set of features (the ones users use the most) in the product. So, please let us know which features you use the most. The list above is a great start. History is high on our list.

Thanks,
Jason

**Comment by ayushindin** [comment]
@jpricketMSFT , @vbarkov I often use **annotate** function to understand who write some piece of code:-)

**Comment by jpricketMSFT** [comment]
Thanks for adding that to the list. Annotate is definitely a cool feature. 
-Jason

**Comment by jpricketMSFT** [comment]
History for a particular file or folder and Rollback (called Revert in IntelliJ) are available in the latest release of the plugin. Look for the commands under the TFVC menu for an item.
Annotate is on the backlog.
Get specific version is under debate (leave it on the command line only or add options to the Sync dialog). 
Keep an eye on the release notes to see when these other features come online.
