### ISSUE TITLE
TFVC Command Line

### ISSUE THREAD

**Issue by chenlong0525** [Microsoft/vso-intellij#41]
The installed version of the TF command line is 0.0.0. The minimum version suggested is 14.0.3. You may run into errors or limitations with certain commands until you upgrade. Follow these upgrade instructions.

[idea.txt](https://github.com/Microsoft/vso-intellij/files/577396/idea.txt)

**Comment by leantk** [comment]
Hi @chenlong0525,

We have been seeing this in some cases. We are making the fix currently and plan to be releasing it soon. I'm going to leave your issue open until we can confirm that our new fix actually does correct the issue for you. Sorry about the trouble and thanks for reporting it.

-Leah

**Comment by chenlong0525** [comment]
How do I make use of it now

**Comment by jpricketMSFT** [comment]
This is most likely caused by your locale settings not being English. We haven't finished the work to call the command line correctly in non-English locales. However, you should be able to use the workaround described in the comments of the blog that announced the release here:
https://blogs.msdn.microsoft.com/visualstudioalm/2016/09/18/tfvc-support-in-preview-for-team-services-plugin-for-intellij-and-android-studio/

Hope that helps,
Jason

**Comment by chenlong0525** [comment]
This problem still appears after the android studio  plugin update

**Comment by jpricketMSFT** [comment]
@chenlong0525 - The current fix forces the CLC to use English when we call it from IntelliJ (this is a short term fix while we consider how best to change the CLC itself). It does this by passing some JVM options to the cmd/sh file thru environment variables. The latest version of the CLC has some script changes to make this work, but you can make the changes yourself to verify that this is the problem.

Follow these steps:
- go to the folder where the Java TF Command Line (CLC) is installed
- open the script file that is being called by IntelliJ (tf.cmd on windows and tf on other OSes)
- somewhere near the end you should see where it launches the jvm and starts the command line process
- look for the environment variable TF_ADDITIONAL_JAVA_ARGS being used.
- If you don't see it being used, you need to get the latest CLC or update the script to pass TF_ADDITIONAL_JAVA_ARGS to the jvm just after the CLC_CLASSPATH variable.
- If it is there, but you are still having this problem, try echoing the value of the TF_ADDITIONAL_JAVA_ARGS variable to a file and seeing what the value is. Post that here and we can try to diagnose it further.

Thanks for helping us troubleshoot these problems. We hope to have the TFVC features bug free and ready for a full release soon. Your help gets us there much faster!

Thanks,
Jason

**Comment by chenlong0525** [comment]
After a few seconds, the tf.cmd window closes automatically

**Comment by jpricketMSFT** [comment]
@chenlong0525 - Hi, can you elaborate on the problem? What tf.cmd window are you referring to? Is something not working the way you expect it to? Can you provide your IDEA logs?
Thanks,
Jason
