### ISSUE TITLE
Commit failed with error KEY_TF_BAD_EXIT_CODE

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#44]
Hi!
In IntelliJ I installed everything as it's said there http://java.visualstudio.com/docs/tools/intelliJ#_tfvc-support-preview
When I try to check in changes to my TFVC repository, I’m getting this error:
“Commit failed with error
0 files committed, 1 file failed to commit: 
KEY_TF_BAD_EXIT_CODE”

Besides, "TFVC (preview)" is disabled in VCS menu.

Best regards,
Kate

[checkin_errorlog.zip](https://github.com/Microsoft/vso-intellij/files/597430/checkin_errorlog.zip)

**Comment by jpricketMSFT** [comment]
Hi Kate,

Thanks for reporting this issue and providing the logs. We have a fix for the TFVC menu being disabled along with a few other fixes. Those should be going out soon. If we can determine what caused your error here, we will get a fix ready for that problem as well.

Thanks for trying it out and helping us improve the product.
Jason

**Comment by bubblef** [comment]
@jpricketMSFT Hi, Jason.
I updated the plugin to 1.109.0. Now I can add nothing to source control. I change classes, add new items. "Add" is disabled and there are not my changes in Version control window tool. 
In logs I can see only warnings:
```
14:11:58.464 |  WARN | ea.tfvc.core.TFSChangeProvider | Failed to get changes from command line. root=/Users/.../AppTFVC/.idea/.idea.AppTFVC/.idea/.name
java.lang.RuntimeException: TF14079: The item U:\Users\...\AppTFVC\.idea\.idea.AppTFVC\.idea\.name is not part of your workspace.  Please perform a get operation on this item.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:333)
	at com.microsoft.alm.plugin.external.commands.StatusCommand.parseOutput(StatusCommand.java:57)
	at com.microsoft.alm.plugin.external.commands.StatusCommand.parseOutput(StatusCommand.java:23)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:142)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:289)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:327)
```

Maybe I do something wrong?

Also, does your plugin support Gated Check-in?

**Comment by jpricketMSFT** [comment]
@bubblef - It looks like you are getting an error from the status command when it tries to parse the output from the command line. Did you change the command line client in any way? It could be a bug, but I am not seeing that error here. The log file should show the command line used to call status as well. Can you try running that command line directly and see what response you get?

No Gated Check-in support right now. Sorry.

Thanks,
Jason

**Comment by bubblef** [comment]
Hi Jason,
Sorry for the delay.
No, I didn't change the command line client. 
I create a new class (IDEA highlights it with a blue color). I run a command to get a status and I get only this:
`<?xml version="1.0" encoding="utf-8"?><status/>` (the same is in the log file)
So, there are no changes for VCS.
It is reproduced on Mac OS. I updated IDEA to 2016.3.

**Comment by jpricketMSFT** [comment]
Hi Kate, 
Can you confirm if your workspace is a Server or Local workspace? We don't fully support Server workspaces yet. For Local workspaces, the status call should detect the new file and return it as a possible add.
Thanks,
Jason

**Comment by bubblef** [comment]
Hi, Jason! 
I updated the plugin to 1.111.0 and I do not have any issues. It works well so far :smiley_cat:

**Comment by jpricketMSFT** [comment]
This is awesome! Thanks for letting us know.

**Comment by hnabbasi** [comment]
Hi, is gated check-in supported yet?

**Comment by minaaboud** [comment]
Hello, 
This morning when I tried to commit changes I got that same error, and received an update for the plugin after the updates I receive this error: 

`-- JAVA_EXCEPTION --- javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized at com.microsoft.alm.plugin.idea.tfvc.core.TFSVcs.getServerContext(TFSVcs.java:275) at com.microsoft.alm.plugin.idea.tfvc.core.TFSFileListener$1.run(TFSFileListener.java:78) at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:267) at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726) at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163) at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:594) at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)


`

any help?

**Comment by minaaboud** [comment]
I'm temporally found a fix for this.
I simply, switched server from manage workspace from TFVC menu  , reconnect to the same server , chosen same workspace, got an error message "I can't choose the same exisitng workspace" , clicked ok, tried to checkin file,   committed file successfully.

**Comment by minaaboud** [comment]
Also I found out that it's a problem with the TFS plugin doesn't store my credentials, every time I close rider. 

when I did the temporarily fix I found my credentials in place. but if I rested the application, it will loose them. 

any help with that ? 
<img width="1023" alt="screen shot 2017-08-23 at 11 35 42 am" src="https://user-images.githubusercontent.com/8300058/29609475-9ee2f8f4-87f7-11e7-8a6a-8d265861cedf.png">

**Comment by leantk** [comment]
Hi @hnabbasi,

We currently still don't have checkin policies in place but they are high on our priority list to get to next. Sorry for the inconvenience!

**Comment by leantk** [comment]
Hi @minaaboud,

Thanks for reporting the issue. I am aware of the credentials not being saved on the IDE restarting. I'm currently looking into that. Other than that, is everything else working for you? The NotAuthorizedException was because your credentials couldn't be found so it was correct of you reload the workspace using the Manage Workspaces dialog. That allows you to re-enter your credentials when they can't be found. They should be saved though and like I said I'm working on that fix.

Thanks,
-Leah

**Comment by minaaboud** [comment]
Thanks guys, you rock, waiting the updates.

**Comment by minaaboud** [comment]
Everything else is working just fine :), so far. been using the IDE for a week.

**Comment by leantk** [comment]
Hi @minaaboud,

The same problem was reported with issue https://github.com/Microsoft/vso-intellij/issues/95. I just attached a newer version of the plugin there with a fix to test out for the password problem. Could you please test it if you have a chance and let me know if it works for you.

Thanks,
-Leah

**Comment by minaaboud** [comment]
okay, will do.

**Comment by minaaboud** [comment]
It's working just fine. I hope you push this updates so all get it 👍 👍 👍

**Comment by leantk** [comment]
Thanks for testing it! The next release (which should be in the next 2 weeks) will have the update so you can upgrade to it and keep the same behavior.

**Comment by Kokochu** [comment]
@leantk Like @hnabbasi I'm also waiting for gated check in support and would be happy to help once you have something you'd like tested.
