### ISSUE TITLE
Failed to get authenticated jaxrs client

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#46]
Hi,
It seems my login session has expired (I'm not sure what went wrong) 
and when I opened my project with enabled TFVC I get this exception:
```
getAuthenticationInfoAsync failed: Failed to get authenticated jaxrs client.
com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: Failed to get authenticated jaxrs client.
```
I attached [the remaining part of the exception](https://github.com/Microsoft/vso-intellij/files/640492/stacktrace.zip)

**Comment by leantk** [comment]
Hi @bubblef,

Sorry to hear you're having issues. If you could answer a few more questions for me, it would help me troubleshoot better. Have you rotated your credentials lately? Were you prompted to enter in credentials at all before that error occurred? 

If you're credentials have changed or the authentication truly expired, you can clear out the old authentication info by opening up IntelliJ (or whichever IDE you are using) and go to Settings (for WIndows) or Preferences (for Mac). Using the left navigation tree, go to "Appearance & Behaviors" -> "System Settings" -> Passwords. Under Passwords, select the option to "Remember the passwords until the application is closed" or "Do not save, forget passwords after restart". The option depends on which version of the IDE you have, but they both do the same thing. Select Apply to save and then restart the IDE. After restart, bring up your workspace and you should be prompted for credentials. With the new credential, you should be back to normal. You can change back the Password setting to whatever you had before.

This is a known issue where if passwords change and/or authentication expires, we do not handle updating the credentials. We have it on our backlog to implement this in the next few releases. If this did not fix your issue though, could you please give me a full log from the IDE by following the last FAQ here:
http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq

Thanks for reaching out to us,
-Leah

**Comment by bubblef** [comment]
Hi Leah,
Thank you for the answer. I cannot reproduce this issue anymore. Now it works well.
