### ISSUE TITLE
Can't Create Workspace

### ISSUE THREAD

**Issue by lhuyviet** [Microsoft/vso-intellij#47]
Hi,
Installed the plugin, but can't create a workspace.
Here are my step:
Start Android Studio
Select Check out project from Version Control
Select Team Service TFVC (Preview)
Select "Team Foundation Server" tab
Select a Repository
Check the box "Edit the workspace before getting sources"
Push button "Create Workspace"
and nothing happens.
Attached the idea.log
Regards,
Huy
[idea.zip](https://github.com/Microsoft/vso-intellij/files/646955/idea.zip)

**Comment by leantk** [comment]
Hi Huy,

Thank for reporting the issue. When you say nothing happens, do you mean the Checkout dialog freezes or does it just disappear with no additional actions being taken? If it is freezing, we have a bug fix that hasn't gone out yet that solves a freezing issue some users have seen. I can give it to you as well to test to see if that solves the issue.

Thanks again,
-Leah

**Comment by lhuyviet** [comment]
If I press one time the "Create Workspace" button, the Checkout dialog doesn't freeze or disappear. But it doesn't do anything. I can still press the Cancel button to close the dialog.

**Comment by leantk** [comment]
Attached is the new plugin with the bug fixes to Create Workspace. Let me know if that makes a difference. If not, could you please send me the new log since I've added some new logging? Could you also try to create a workspace with and without the "Edit workspace before getting sources" checked? I want to see if you get the same behavior or not.

[plugin.idea-1.109.1-github-47.zip](https://github.com/Microsoft/vso-intellij/files/652286/plugin.idea-1.109.1-github-47.zip)

Thanks for your patience as we debug,
-Leah

**Comment by leantk** [comment]
Also if you aren't sure how to install the plugin from a zip file, you jut have to go to File -> Settings and then the Plugins tab. There is an option "Install plugin from disk" that will let you select the zip file.

**Comment by lhuyviet** [comment]
The plugin provided did solve the issue. But uncovered another issue, Once the project opened, all file are in read-only. When we try to edit a file, we will get a window that give option to clear the read-only status. But we can't select the option to use the version control integration.
![clearreadonlystatuswindow](https://cloud.githubusercontent.com/assets/24530787/21242465/736dc724-c2e2-11e6-8769-915265b9baa1.jpg)

**Comment by leantk** [comment]
Hi @lhuyviet,

A new version of the plugin was released last week (version 1.111.0) should solve the issue you mentioned with the files being read-only. All workspaces should be local workspaces and by default a local workspace should be created but in some cases server workspaces were being created based on personal configurations. We force a local workspace to be created now so if you try to checkout the repository again with the updated plugin, you should be able to edit the files. Let me know if the update works for you.

Thanks and sorry for the inconvenience,
-Leah
