### ISSUE TITLE
Commit > select work items bugs

### ISSUE THREAD

**Issue by fmonts** [Microsoft/vso-intellij#48]
There are 2 bugs in the dialog that let you select work items to link to a git commit: 

1. Sorting by ID is wrong (I'd like to show newest first, but it looks like 100 < 11 < 110 < 12...)

2. When I select multiple choices with CTRL, some items (or all, sometimes), are selected wrong. For example I select 121, 131, 132, 133, 134, 135 and I click OK. In the commit message I get totally different ones (16, 110, 35, 29, 95)
This must also be related to sorting, because if I don't change the sorting it works fine.

**Comment by jpricketMSFT** [comment]
@fmonts - Thanks for reporting these bugs. We will work on these as soon as we have time. I agree with your assessment of the second issue. It is most likely related to the sorting.
Thanks, Jason

**Comment by venkatteshb** [comment]
TFS Version: 14.102.25423.0
Visual Studio Team Services plugin version: 1.111.1
IntelliJ IDEA 2016.3.3

Unable to select work items from queries in 'My Queries'. It says "Unexpected errors were encountered while loading work items. The list may not be complete" while in the "Work items" tab in the "9: Version Control" window. It was defaulting to the "Assigned to me" query in TFS, so I tried changing the filter "Assigned to me" query in TFS but plugin still remembers the previous query used for "Assigned to me" query.

**Comment by leantk** [comment]
Hi @venkatteshb,

We have the Assigned to Me query hard coded so even if you change it through the browser it won't make a difference. Do you see any work items appear in the tab? If so, can you right click on them to see the dropdown menu? Would you be able to send us a log of this error? You can follow the directions given in the last FAQ [here ](http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq) to get the log and then you can either attach it here or email it to me directly at leantk@microsoft.com.

**Comment by leantk** [comment]
@fmonts the latest release of the plugin 1.113.0 has the fixes for this. Thanks for reporting the problems and let us know if you see anything else.

**Comment by fmonts** [comment]
Thank you, it seems fixed but there is a regression: now I see only 16 work items (I have hundreds). Even if I search for a work item that exists, it doesn't find it

**Comment by jpricketMSFT** [comment]
@fmonts - This was another fix that we made. You should only see work items that are not "closed" in the list now. Let me know if there is a scenario where you want to see those items in the list as well or if you don't see items that should be in the list.

Thanks,
Jason

**Comment by fmonts** [comment]
It happens to make small changes or hotfixes to features already closed, and to not reopen them just for laziness, but it makes sense

**Comment by fmonts** [comment]
Anyway not only closed work items are missing, but also those in custom columns (for example I have one with "State mapping: New", but I don't see its work items)

**Comment by leantk** [comment]
Hi @fmonts,

I'm trying to reproduce your issue. So you have some work items in a custom column you made on your board that aren't showing up for you? What type of work item are they? Do you remember seeing them before the last plugin update? Could you do a test for me on one of the missing work items please? In your browser paste the following link but insert your account URL and work item number in it: https://<account_name>.visualstudio.com/_apis/wit/workitems/<work_item_number>?$expand=all

In the results, see if there is a field returned called "ClosedBy". If so, please let me know.

Thanks,
-Leah

**Comment by fmonts** [comment]
No, there is no closedBy but I found out why, it's because of: ````where system.assignedto = @me````

Since they are new, some of them aren't yet assigned to anybody, so it's always been like this and I didn't notice. 

Thank you very much for your work.
