### ISSUE TITLE
kerberos in TFS2017

### ISSUE THREAD

**Issue by HackPoint** [Microsoft/vso-intellij#52]
We lately installed the TFS2017 that uses authentication kerberos protocol. The plugin is unable to connect because of it supports only NTLM.

The error I get **"connection reset"** - it is blocked on server handshake.
If more information is required please tell.

Thanks,
HackPoint

**Comment by madhurig** [comment]
@HackPoint: We are able to connect to TFS 2017 servers successfully. Can you please provide more details?
We have instructions on how to collect the logs at the end of this page [here](http://java.visualstudio.com/Docs/tools/intelliJ). If you could zip up the logs and attach them here or email leantk at microsoft.com, that will help.

Thanks,
Madhuri

**Comment by leantk** [comment]
Closing since there has been no follow-up. Please reopen if the issue still persists.

Thanks,
-Leah
