### ISSUE TITLE
Connect Android Studio to Team Foundation Version Control

### ISSUE THREAD

**Issue by VishalBPatel** [Microsoft/vso-intellij#57]
When I connect android studio with Team Foundation Version Control Preview I get following error

Plugin Error - visual studio team service threw an uncaught exception RunTimeException.

Also some user also get the same error.You can see that error in following URL.

http://stackoverflow.com/questions/39798652/connect-android-studio-to-team-foundation-version-control

Thanks.

**Comment by leantk** [comment]
Hi @VishalBPatel,

Could you do me a favor and send me the Android Studio log which will contain more information please? You can get the log by following the steps in the last FAQ here:
http://java.visualstudio.com/Docs/tools/androidstudio#_frequently-asked-questions-faq

You can attach the log to this issue or email me at leantk@microsoft.com if you'd rather not post it.

Thanks,
-Leah

**Comment by leantk** [comment]
Closing since there has been no follow-up. Please reopen if the issue still persists.

Thanks,
-Leah
