### ISSUE TITLE
It takes 5 seconds to add a new class to TFVC (IDEA)

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#60]
Hi!

Adding a new class to TFVC takes up to 5 seconds. It does not feel great. I attached [log.txt](https://github.com/Microsoft/vso-intellij/files/824459/log.txt). What can be wrong?

This progress bar appears for every VCS action.
![2017-03-07_16-14-37](https://cloud.githubusercontent.com/assets/22168773/23657979/c68f8c4e-0351-11e7-96ce-df9c0c4cd169.png)

**Comment by leantk** [comment]
Hi @bubblef,

It looks like you are using the 14.0.3 version of our command line client. The plugin calls out to that to perform the TFVC actions. Some performance improvements have been made in more recent versions of it. Would you mind trying to use the latest 14.111.1 version found at the link below and see if that helps improve the timing at all? If not, please let me know so I can further investigate. 

https://github.com/Microsoft/team-explorer-everywhere/releases

Thanks!
-Leah

**Comment by bubblef** [comment]
Hi Leah,
I've tried it with the 14.111.1 version, but unfortunately it doesn't help.

**Comment by leantk** [comment]
Ok then I will log this as a bug on our end. Thanks for trying the update though. We have performance improvements planned for the command line client but hearing about experiences like this helps us prioritize the work better. 

Thanks again,
-Leah

**Comment by bubblef** [comment]
Hi Leah,
It's reproducing on MacOS and on Windows as well.

**Comment by leantk** [comment]
Ok I made some changes to the plugin that caused me to see performance improvements on my Mac. Could you test this out and let me know if you see any difference please? (Make sure you are still using the 14.111.1 or higher version of the CLC or it won't work)

Thanks,
-Leah
[plugin.idea-1.115.3.zip](https://github.com/Microsoft/vso-intellij/files/848387/plugin.idea-1.115.3.zip)

**Comment by bubblef** [comment]
Hi Leah,
Sorry for the delay. 
The plugin's performance is better with the 1.115.3 version. It takes 2-3 seconds to add a new file.

**Comment by leantk** [comment]
Good to hear @bubblef. I'll close this issue then but if you see anymore performance problems please feel free to reopen this.
