### ISSUE TITLE
The plugin requires admin privileges (elevation prompt) at startup

### ISSUE THREAD

**Issue by shalupov** [Microsoft/vso-intellij#62]
Current plugin version uses regedit.exe to register protocol handler for vsoi urls.
Unfortunately it 1) uses regedit.exe which requires elevation prompt 2) registers protocol handler system-wide, not per user.

Since IDE could be installed per user basis and using of TFS plugin is ultimately user choice I suggest to register protocol handler in HKCU and use "reg.exe import" to import .reg file.

Why it matters: 
* Rider IDE is going to bundle TFS plugin, but not all users use TFS, so elevation prompt on the first start is undesirable for Rider users.
* Even for TFS users JetBrains Toolbox App manages installations per-user, so installing protocol handler for all users may potentially break some things for other users on the same machine.

**Comment by leantk** [comment]
Hi @shalupov,

Thanks for the recommendations for the fix. You can see the changes at this commit https://github.com/Microsoft/vso-intellij/commit/26e3a30c2b1e4af69b0d26df03aadafe69b106a9. I have tested them out and do not see the elevation prompt anymore during install and the protocol handler still launches correctly from the browser. 

Thanks again,
-Leah

**Comment by shalupov** [comment]
Thanks!
