### ISSUE TITLE
TS plugin requires Git when I want to select Work items on commit using TFVC (not Git)

### ISSUE THREAD

**Issue by niiiksh** [Microsoft/vso-intellij#65]
Following error appears: "The Team Services plugin requires Git settings to be configured. Fix the Git Version Control settings to point to a valid Git executable." I use TFVC repo but this option asks me to install Git.

**Comment by jpricketMSFT** [comment]
@niiiksh - this seems like a bug. We will try to investigate and fix this as soon as possible.
Thanks for reporting this issue.

**Comment by leantk** [comment]
I believe this has been fix and released. If you are still seeing this issue please re-open the issue
