### ISSUE TITLE
Failed to create pull request

### ISSUE THREAD

**Issue by Michael2109** [Microsoft/vso-intellij#68]
```
Failed to Create Pull Request: Authenticating to the server for Git repository '$URL' was not successful. Provide valid credentials and try again.
```
When creating a pull request a window will appear (I'm assuming to type in the credentials) but it closes before displaying anything. After this an Authorization Exception is shown in the Event Log. 
```
AuthorizationException: getAuthenticationInfoAsync failed: Failed to get authenticated jaxrs client.
```
We are using a proxy so this may be the cause of this issue.

**Comment by yacaovsnc** [comment]
Hi @Michael2109, does your proxy server require authentication?  

What is your java version and OS?  I want to figure out why the browser auto closes, sounds like it crashed.  

If this is a proxy issue, you may take a look at #43, I believe the proxy setting will be propagated to the browser window (which is the one that auto-closed).  If your proxy requires authentication, we may need to setup device flow for it to work.

**Comment by Michael2109** [comment]
Using Java 1.8.0_111 and Windows 7. 

The proxy requires authentication. I've added the proxy settings in "Appearance & Behavior -> System Settings -> HTTP Proxy" and checked the connection but the issue still occurs. 

I was thinking that if the browser tried opening without using the proxy authentication it possibly could cause it to break down. 

I did see #43 but was a bit unsure as to why it was closed seeming as this issue didn't appear solved from the comments. 

Let me know if you need any more information.

**Comment by yacaovsnc** [comment]
The underlying browse window doesn't support authenticated proxy due to [#18](https://github.com/Microsoft/oauth2-useragent/issues/18).  

To fallback to device flow, you can add this __-DuserAgentProvider=none__ to your idea.exe.vmoptions (or idea64.exe.vmoptions, I modified both) file:
![image](https://cloud.githubusercontent.com/assets/10119737/24157301/6929e976-0e2f-11e7-918e-fb89a05306eb.png)

Restart IntelliJ you should be prompted with a dialog box instead of the browser:
![image](https://cloud.githubusercontent.com/assets/10119737/24157406/a220d492-0e2f-11e7-9cc5-bd4709aa475b.png)

Please click on the "https://aka.ms/devicelogin" link, and copy/paste the code in there.  After you login via browser, click on "Continue" and you should be logged in.  

This will bypass the proxy issue on the browser.

**Comment by Michael2109** [comment]
I've added the line to both the 32bit and 64bit versions and restarted twice now. The dialog box doesn't seem to appear and instead it opens with the original browser.

**Comment by yacaovsnc** [comment]
Hmmm, this is odd.   How about if you create a custom VM Options file and add the setting there?

![image](https://cloud.githubusercontent.com/assets/10119737/24160303/caf5cc8a-0e37-11e7-9550-b06e8fa513d3.png)

**Comment by Michael2109** [comment]
This option is grayed out as we use a version of IntelliJ that has been changed by the company we are working with sorry. Are there any other methods of getting around this?

**Comment by yacaovsnc** [comment]
Ah, unfortunately currently the behavior can only be altered by properties.  If your intelliJ instance is shielded from altering properties, we can't launch this device flow.

I will have to discuss internally on how to proceed at this point.  It appears we must find an alternative to expose this setting.

**Comment by Michael2109** [comment]
Okay thanks for your help!

**Comment by yacaovsnc** [comment]
The latest 1.116.1 plugin should search for a setting file in addition to the vmoptions file.  On Windows system, it searches for the file at:
`%LOCALAPPDATA%\Microsoft\VstsAuthLib4J\settings.properties`

On my system:
`2017-04-11 14:54:19,958 [  87002]   INFO - oft.alm.helpers.SettingsHelper - Searching for C:\Users\yacao\AppData\Local\Microsoft\VstsAuthLib4J\settings.properties`

The content of this file is just:
`userAgentProvider=none`

**Comment by leantk** [comment]
Closing since there has been no follow-up. Please reopen if the issue still persists.

Thanks,
-Leah
