### ISSUE TITLE
Error installing plugin into JetBrains MPS

### ISSUE THREAD

**Issue by eugenschindler** [Microsoft/vso-intellij#69]
System: Windows 10, JetBrains MPS 3.4.3
When I install the plugin from the plugin repository and restart MPS, then I get the following error message:
![image](https://cloud.githubusercontent.com/assets/6429350/24465113/481a7b8c-14ac-11e7-9f1c-b2a2184fdfa5.png)
In order to fix this error with the installed plugin, I had to do the following:
 * Download slf4j manually
 * Remove the line com.microsoft... from %HOME%/.MPS34/config/disabled_plugins.txt
 * Copy at least slf4j-api jar (where LoggerFactory is locate, but I also included slf4j-jdk, slf3j-log4j, and slf4j-simple jars) to %HOME%/.MPS34/config/plugins/com.microsoft.alm/lib
This at least made sure that there is no error and no automatic disabling of the plugin.
You may want to prepackage the slf4j jars so that this error doesn't happen anymore

**Comment by jpricketMSFT** [comment]
@eugenschindler - thanks for reporting the issue and your work around. We don't package slf4j with our plugin because IntelliJ Community edition and most other JetBrains IDEs built on IntelliJ already have it installed. We will try to work with the JetBrains folks to figure out how best to handle this problem.

Thanks again,
Jason

**Comment by leantk** [comment]
Not that we won't look at this further, but MPS 2017.1 comes with slf4j packaged with it. If you don't want to deal with downloading the slf4j jar and adding it to MPS yourself, I would suggest upgrading to that version for now.

**Comment by eugenschindler** [comment]
OK, thanks. If you checked 2017.1, I believe you that it will work :)
Currently, the team I work with cannot switch immediately to 2017.1, but the workaround will do fine for now, so for me it's not an issue. Do you want me to keep it open for MPS 3.4 or shall I close it?
