### ISSUE TITLE
Only git repositories are shown

### ISSUE THREAD

**Issue by eugenschindler** [Microsoft/vso-intellij#70]
When connecting to a TFS server, no team projects are shown and also no TFVC repositories. The only thing the server shows are the available git repositories on the server (without showing to which team projects they belong). This makes the TFVC repositories inaccessible from IDEA and/or MPS.

**Comment by jpricketMSFT** [comment]
@eugenschindler - Can you describe exactly what steps you are taking in the UI? Are you starting from the Checkout from Version Control menu? There should be 2 options there, Team Services Git and Team Services TFVC. If you choose Git, we only show Git repositories. If you choose, TFVC we show TFVC repositories. Is this the source of the confusion? If the git repository name is not unique, the Team project is in the second column to help distinguish them.

Thanks,
Jason

**Comment by eugenschindler** [comment]
Hi @jpricketMSFT, 

Thanks for your quick reply.
I just installed the plugin from the JetBrains repository (version 0.92.1 from 2015). And now I see it: when I try to check out using the TFS plugin, I only get an option to check out from git:
![image](https://cloud.githubusercontent.com/assets/6429350/24514693/73667dc6-1575-11e7-89b9-b34f474d1e2b.png)
Could it be that the "old" version in the plugin repository (because it's from 2015) doesn't support TFVC?
I tried to get the newest version, but your releases only contain zips with source code, no prebuilt plugins.
When I try to build it myself (following README.md), it fails for me at step 1 (./gradlew.bat copyDependencies) reporting that it cannot find the packages org.apache.commons.lang and org.slf4j. If you can tell me where to obtain a binary verison of one of your newer releases (or give me some hints as to how to get unstuck building the plugin from sources), I can try the newest version and see if that one gives other options than only the one shown in the picture above.

**Comment by eugenschindler** [comment]
Never mind, I found the newest binary version on https://plugins.jetbrains.com/plugin/7981-visual-studio-team-services. And indeed, the older version (which is the default available version when searched from inside the MPS tool) doesn't have TFVC capability, only git. You may want to update this default to a newer (the newest?) version.
