### ISSUE TITLE
MPS files ignored by the plugin

### ISSUE THREAD

**Issue by eugenschindler** [Microsoft/vso-intellij#72]
When using the plugin with JetBrains MPS, then only java files are shown as changed files. The MPS files (*.mps, *.msd, *.mpl) seem to be completely ignored and thus it is impossible to see how the working copy of these files changed with respect to the checked-in versions.
I tried looking for settings in the plugin, but wasn't able to find anything about files or file extensions that are not considered by the plugin.
Would it be possible to make it so that other files than java files (or if necessary only specifically the MPS extensions) are taken into account when viewing differences between working copy and checked-in versions (Ctrl+K in MPS)?

**Comment by leantk** [comment]
Hi @eugenschindler,

I'm sorry to hear about your issue. I tried to reproduce your issue in MPS 2017.1 (I saw from another issue you're using 3.4) but I get all my mps files to show up changed in the Local Changes window. Could you do me a favor please and drop down to the command line and run a "<path to the tfs command line tool>\tfs.cmd status" from inside your project directory? I want to see if the IDE is having the issue with reporting the changes or if the command line tool is not detecting them at all. 

Could you also attach a log for me please. It might tell me more about your problem. You can follow the steps in the last FAQ to find the log file: http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq 

Thanks,
-Leah

**Comment by eugenschindler** [comment]
Hi Leah,
Thanks for your quick reply and all the information provided. It seems that we misconfigured the VCS root. With TFVC it works a bit different that with git apparently. Using tf.cmd was very helpful as well with debugging commit problems that we had due to a custom policy on the TFVC server side.
With the new version (116), everything seems to work quite fine and performance also has improved.
Thanks again!

Greetings,
Eugen
