### ISSUE TITLE
"Performing VCS refresh..." - Dialog stays active for minutes

### ISSUE THREAD

**Issue by Cedware** [Microsoft/vso-intellij#73]
When I'm trying to commit changes to TFVC aDialog shows up, which cintains the message "Performing VCS refresh...", most times the dialog stays there for a very long time until the checkin dialog gets opened.
![Screenshot](https://cloud.githubusercontent.com/assets/13673693/24951822/f256edc8-1f75-11e7-875f-def4830d14f5.PNG)
I don't have this problems with other Version controll systems, so I think it's a bug of the plugin

**Comment by leantk** [comment]
Hi @Cedware,

Do you know what version of the TF command line and version of the plugin you are using? Also what OS are you on? 

Thanks,
-Leah

**Comment by Cedware** [comment]
Plugin: 1.116.1
TF command line:  14.114.0.201703081734
I'm running on Windows 7 Professional

**Comment by leantk** [comment]
Thanks for the quick response. We were seeing performance issues on older TF and plugin versions but you have the latest. Would you mind sending me a log of you performing a commit so I can try and track down what exact call is taking so long? You can get a log by following the last FAQ here: http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq

Thanks again,
-Leah

P.S. If you don't want to attach the log to this issue for privacy reasons please feel free to email it to me at leantk@microsoft.com

**Comment by leantk** [comment]
Closing since there has been no follow-up. Please reopen if the issue still persists.

Thanks,
-Leah

**Comment by C-Romeo** [comment]
Same problem. Environment info:
-Android Studio 2.3.3
-Visual Studio Team Services plugin 1.122.0
-TEE-CLC-14.119.2
-Windows 8.1 Enterprise

**Comment by m1gu3l** [comment]
Same problem.
-IntelliJ Ultimate 2017.2.2
-Visual Studio Team Services plugin 1.122.0
-TEE-CLC-14.120.0
-Windows 7 Professional
