### ISSUE TITLE
Unsigned vsoi app ?

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#76]
Hi!
On Mac when opening Rider with the bundled plugin I get a warning: 
![2017-05-07_16-25-20](https://cloud.githubusercontent.com/assets/22168773/25784894/8bda3804-337d-11e7-9ee3-d229f2548fe3.png)
Looks like vsoi app is unsigned.

**Comment by yacaovsnc** [comment]
Thanks for reporting this issue.  I have created a backlog item to sign it.

**Comment by leantk** [comment]
Hi @bubblef,

I'm working on getting a cert through the proper channels and signing the app. The app registers our protocol handler in case you were wondering.

**Comment by leantk** [comment]
The app was signed in commit https://github.com/Microsoft/vso-intellij/commit/e1eef428a2ad0a9623b1f2b75ff85f367a35c5e0
