### ISSUE TITLE
High CPU usage if there is no Internet connection

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#77]
Hi!
If I turn off the internet connection CPU usage goes up too high in 10-20 seconds. It seems the plugin can cause this. When I disable the plugin, CPU/disk usage goes down. Here is a [snapshot](https://github.com/Microsoft/vso-intellij/files/981968/RS-171.4456.67_admin_05.05.2017_17.59.41.zip) created with Yourkit 2016.2. 

It is reproducible both in IDEA and Rider on Windows and MacOS.

**Comment by yacaovsnc** [comment]
Thanks for reporting.  Will investigate.

**Comment by leantk** [comment]
Fixed in current release 1.119.0
