### ISSUE TITLE
Problem connecting to microsoft account when checkout VCS

### ISSUE THREAD

**Issue by net2h** [Microsoft/vso-intellij#8]
When checkout from version control i login microsoft account and get Unable to connect to the IDE. Please restart the IDE and retry authentication. No way to pass...
!
[capture](https://cloud.githubusercontent.com/assets/16607640/12485832/442ddbc8-c060-11e5-9534-fc2219e09c90.PNG)

Worked perfectly on Linux on same plugin version / IDE

Platform : windows 7 : php storm 10.0.3

**Comment by yacaovsnc** [comment]
We are using this library to authenticate:
https://github.com/MSOpenTech/azure-activedirectory-interactive-auth-library-for-java/blob/master/src/ad-interactive-auth/src/com/microsoftopentechnologies/adinteractiveauth/Program.java

It seems you hit the error on line 153.  That happens when the local webserver (https://github.com/MSOpenTech/azure-activedirectory-interactive-auth-library-for-java/blob/master/src/com/microsoftopentechnologies/auth/webserver/AADWebServer.java) fails to start.  

Unfortunately I don't see any logging from that library.  Does your problem persist after a restart?   If it does, we can start debugging with a standalone instance of webserver and see if there is any settings that prevented the webserver from coming up.  

Thanks.

**Comment by net2h** [comment]
I restarted several times the software even Windows but no changes.

Nicolas

**Comment by yacaovsnc** [comment]
@net2h hi Nico, is your windows firewall on?  If so, could you please turn it off for a brief period and try again?  I want to see if there is any rules blocking the webserver from binding to a local port.

Thanks a lot!

**Comment by net2h** [comment]
@yacaovsnc No firewall on, i ended by pushing externaly, i hope new version will solve this...

**Comment by ycao233** [comment]
@net2h sorry about the trouble.  We do have another implementation of the auth flow in the works that should solve the issue you are facing.  However currently it's still a work in progress.  We will definitely try to make it work soon.

What version of Java are you running phpStorm on?  The new Auth flow works with Java 1.7+ currently.

**Comment by yacaovsnc** [comment]
@net2h sorry about the trouble. We do have another implementation of the auth flow in the works that should solve the issue you are facing. However currently it's still a work in progress. We will definitely try to make it work soon.

What version of Java are you running phpStorm on? The new Auth flow works with Java 1.7+ currently.

**Comment by net2h** [comment]
@yacaovsnc i run on 1.8.072 i'll wait for the new version !

**Comment by yacaovsnc** [comment]
@net2h with the latest plugin version 0.96.0 (http://plugins.jetbrains.com/plugin/7981), we have added an another authentication implementation that should solve the problem you are seeing on Windows.  

To enable that, in your idea.exe.vmoptions (or idea64.exe.vmoptions if you are using idea64.exe), add this JVM option: 
-DuseJavaFxAuthLibrary=true

Let me know if you are unblocked from Windows with workaround.

Thanks!

**Comment by net2h** [comment]
@yacaovsnc i updated to 0.96.0, add -DusejavaFxAuthLibrary=true to Phpstorm64.exe.vmoptions and i got exactly the same error on login.

**Comment by yacaovsnc** [comment]
"-DusejavaFxAuthLibrary=true" 

Can you please confirm the case?  "Java" should be camel cased.

**Comment by net2h** [comment]
-DusejavaFxAuthLibrary=true i what i entered and added also to PhpStorm.exe.vmoptions and got the same error

**Comment by yacaovsnc** [comment]
@net2h yeah the correct case is: "-DuseJavaFxAuthLibrary=true"  

Make sure you use upper case "J" in your setting.

**Comment by net2h** [comment]
@yacaovsnc great job, it works now.

**Comment by yacaovsnc** [comment]
Great!!  Thanks a lot @net2h for your patience and helping us fixing this issue.  

This new auth library still needs some work and we will keep it as a secondary experimental library for now, later on when it's matured we will assess whether we will switch to the new lib.  

Glad you are unblocked for now.
