### ISSUE TITLE
Link is not clickable 

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#83]
Hi!
Could you please make the link clickable in this popup?
![2017-05-24_15-38-51](https://cloud.githubusercontent.com/assets/22168773/26407521/0d86fe54-40a4-11e7-8610-66e558ef04ae.png)

**Comment by leantk** [comment]
Fixed with commit https://github.com/Microsoft/vso-intellij/commit/3faf0f970552cefc1d01ed661c7a3754dda4e839

This will go out in the next release. Thanks for reporting!
