### ISSUE TITLE
Unable to import local project into a team foundation server collection

### ISSUE THREAD

**Issue by janiaswin** [Microsoft/vso-intellij#9]
There is an issue while trying to import a local project into team foundation server. The import wizard does not seem to fetch the projects listed under a collection although the connection to the tf server is successful

**Comment by madhurig** [comment]
Thank you for contacting us. The plugin only supports Git, so we only show "Git" team projects in the import wizard and "TFVC" team projects are not shown. Are you seeing "Git" team projects missing. It appears you are using an on-premise Team Foundation Server. What version of TFS are you using? 

Regards,
-Madhuri

**Comment by janiaswin** [comment]
Thank you for the reply.

We have the 2015 TFS version for our on-premise operations. Does it mean if
we convert our tfs project (hosted in link http://serveraddress:8080/tfs/)
to a git project the plugin with list for import?

Regards,
Aswin Jani

**Comment by madhurig** [comment]
TFS 2015 RTM does not support team projects that support both TFVC and Git, converting your TFS project from TFVC to Git is also not possible. I can see 2 solutions for you: 
(1) Upgrade to TFS 2015 Update1 if possible. That version of the TFS server allows both TFVC and Git repositories in the same team project. We will publish a change to the plugin this week that will allow you to import into those kind of "hybrid" team projects 
(2) You can create a new "Git" team project on your server to import your Git projects into. You will have to use Visual Studio to create the team project, we don't support that in IntelliJ.

Hope this helps. 

Regards,
Madhuri
