### ISSUE TITLE
Add message if checkin failed due to "file is locked in workspace"

### ISSUE THREAD

**Issue by julia-vaseva** [Microsoft/vso-intellij#92]
If a file is locked in another workspace, I would expect to see a more informative message.

Repro:
1. Check-out project from Version Control via Team Service TVFS to the 1st workspace and check-in files for edit
2. Check-out project from Version Control via Team Service TVFS to the 2d workspace
3. Edit a file in the 2d workspace and try to check-in
Expected result:
A message "The file is locked in another workspace occurs"
Actual result:
A message occurs, but there is no useful information in it. See screenshot

![image](https://user-images.githubusercontent.com/30112159/28871780-c268e5dc-778e-11e7-92dc-77939cac0635.png)

**Comment by leantk** [comment]
I made the fix with commit https://github.com/Microsoft/vso-intellij/commit/595101bb44b6a03ae18f60a432f838834f46b674 and it will go out in upcoming 1.122.0 release

**Comment by leantk** [comment]
I'm going to close these as fixed but if you still think there is an issue please reopen them.
