### ISSUE TITLE
Add message if checkin failed due to "A newer version of file exists on the server"

### ISSUE THREAD

**Issue by julia-vaseva** [Microsoft/vso-intellij#93]
If there is a newer version of a file on the server, I would expect to see a more informative message.

Repro:
1. Check-out project from Version Control via Team Service TVFS
2. Change a file on the server
3. Do not update the file and edit it
4. Try to check-in the file

Expected result:
A message "A newer version of file exists on the server"
Actual result:
A message occurs, but there is no useful information in it. See screenshot
![image](https://user-images.githubusercontent.com/30112159/28872549-5eaa09e6-7792-11e7-88ba-bb7801d373f8.png)

**Comment by leantk** [comment]
I made the fix with commit https://github.com/Microsoft/vso-intellij/commit/595101bb44b6a03ae18f60a432f838834f46b674 and it will go out in upcoming 1.122.0 release

**Comment by julia-vaseva** [comment]
@leantk Thank you for the quick fixes!

**Comment by leantk** [comment]
I'm going to close these as fixed but if you still think there is an issue please reopen them.
