### ISSUE TITLE
Plugin doesn't remember passwords

### ISSUE THREAD

**Issue by rguillens** [Microsoft/vso-intellij#95]
Hi there:
I've been facing a problem using this plugin. Every time I open the IDE and go to Pull Requests or WorkItems tabs in Versioning area, the plugin ask me for credentials, I authenticate and check the Remember option, but my credentials are forgotten when I close de IDE.
Nevertheless, the option **Checkout from Version Control -> Team Services Git** remembers my password as expected.

This is my current scenario:

IntelliJ IDEA 2017.2
Build #IU-172.3317.76, built on July 15, 2017

Plugin: Visual Studio Team Services version 1.122.0

Windows 10 workstation, not part of Windows Domain

Thank you

**Comment by leantk** [comment]
Hi @rguillens,

Thanks for reporting your issue. Just a couple additional questions. First are you using multiple repositories with different Team Services accounts in IntelliJ or is it the same repository and the same account all the time? Also, in the Settings menu, do you have the option to store your passwords in KeePass enabled? You shouldn't be prompted upon every start of the IDE so this is unexpected behavior and we can figure out the issue.

![image](https://user-images.githubusercontent.com/13628312/29122388-24962052-7ce0-11e7-9868-6a6faaf78d59.png)

Thanks,
-Leah

**Comment by rguillens** [comment]
Hi:
I use multiple repositories, but just one account and one Team Services Server. Store password on KeePass option is enabled.
Thanks

**Comment by leantk** [comment]
@rguillens I'm going to try and reproduce this on my end and see if I can get the same result. If so that will make it easier to debug going forward. Thanks again for letting us know and I'll get back to you with some answers. 

-Leah

**Comment by leantk** [comment]
Hi @rguillens,

I made some changes and I think I have fixed the issue. Would you mind testing out this custom build of the plugin with the fix and see if there is any difference? All you need to do is download this 
[plugin.idea-1.122.0-PwFix.zip](https://github.com/Microsoft/vso-intellij/files/1256870/plugin.idea-1.122.0-PwFix.zip) zip but don't un-zip it. In the IDE, go to File -> Settings -> Plugins and then choose "Install plugin from disk" and select the downloaded zip file. Then restart the IDE to pick up the changes. After that see if your passwords are saved when you open and close the IDE.

Thanks,
-Leah

**Comment by leantk** [comment]
Release 1.123.0 should solve this issue. Please reopen if you're still seeing the problem persist. 

Thanks again,
-Leah
