### ISSUE TITLE
"Performing VCS refresh..." - Dialog stays active for long times

### ISSUE THREAD

**Issue by chenguandu** [Microsoft/vso-intellij#96]
When I'm trying to commit changes to TFVC aDialog shows up, which cintains the message "Performing VCS refresh...", most times the dialog stays there for a very long time until the checkin dialog gets opened.
Screenshot
![Screenshot](https://cloud.githubusercontent.com/assets/13673693/24951822/f256edc8-1f75-11e7-875f-def4830d14f5.PNG)

[logs](https://github.com/chenguandu/test/blob/master/idea.log)

Plugin: v1.122.0
TF command line: 14.120.0.201706271643
OS : Windows 10

**Comment by leantk** [comment]
Hi @chenguandu,

Thanks for reporting the issue. The log that you linked to doesn't show the commit dialog being opened. Would you mind restarting the IDE, trying to do a commit, then closing the IDE and getting the log from that please? Also about how files are in your repo? I'm wondering if we aren't scaling well.

Thanks,
-Leah

**Comment by chenguandu** [comment]
[https://github.com/chenguandu/test/blob/master/idea.log](https://github.com/chenguandu/test/blob/master/idea.log)

There are 929 files in the project, total size : 5.50 MB,  one file changed only.

Thanks

**Comment by leantk** [comment]
It looks like the performance is bad because it's detecting ~630 new files in your workspace. Do you ever intend to checkin these files? I ask because they are under build directories or the .idea directory and if you have no intention of checking them in you can set them to be ignored which will greatly improve your performance. If you create a .tfignore file in your root directory and add the paths below (I think these were the main path with the new files) then they will be ignored by the version control system.

E:\TFS\VS\byd_b\build\
E:\TFS\VS\byd_b\app\build
E:\TFS\VS\byd_b\.idea

Let me know if this helps or if you don't want to ignore these files. 
Thanks,
-Leah

**Comment by C-Romeo** [comment]
Same problem. Environment info:
-Android Studio 2.3.3
-Visual Studio Team Services plugin 1.122.0
-TEE-CLC-14.119.2
-Windows 8.1 Enterprise

**Comment by leantk** [comment]
Hi @C-Romeo,

Do you happen to have a large amount of unversioned files in your workspace? Could I get a log from you of the issue so I could try and pinpoint the exact call that is causing the slowdown please? You can follow the instructions here for turning on debugging and getting the log: https://java.visualstudio.com/Docs/tools/androidStudio#_frequently-asked-questions-faq

Thanks,
-Leah

**Comment by leantk** [comment]
Thanks for the info @stephenmcd1. The ~11,000 unversioned files will definitely lead to some performance issues lol. I know you said it hasn't been a big issue for you (which is surprising) but if it does become something that bothers you, you can use the .tfignore file like I mentioned above and it will stop processing those files for status.

**Comment by chenguandu** [comment]
Hi @leantk 
I had added the files to .tfignore, but no effect，
now i using the visual studio instead.
Thanks

**Comment by RachealRileyManda** [comment]
To resolve this:Run
**git clean -n** //this will show you which unversioned files will be deleted
Then run **git clean -fx**to removed ignored and unignored files.
Other alternatives:
git clean -f -X

You should make sure you are deleting files that you are 100% you dont require.
